version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    ignore:
      - dependency-name: "pyTelegramBotAPI"
        versions: ["3.7.3"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    ignore:
      - dependency-name: "googletrans"
        versions: ["4.0.0-rc1"]
