version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "pyTelegramBotAPI"
        versions: ["3.7.3"]
      - dependency-name: "googletrans"
        versions: ["4.0.0-rc1"]
